# -*- coding: utf-8 -*-
"""SARIMAprevisão.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9Ozu9ddJ0wCzmL9dTw3Cu8lwVEADQ2U
"""

#carregar os pacotes
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import statsmodels.api as sm
from datetime import datetime

from statsmodels.graphics.tsaplots import month_plot, quarter_plot
from statsmodels.tsa.seasonal import seasonal_decompose
from pandas.plotting import autocorrelation_plot
from statsmodels.tsa.stattools import acf, pacf
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.statespace.tools import diff
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.gofplots import qqplot
from statsmodels.stats.stattools import jarque_bera
import scipy.stats as sct
from scipy import stats
from statsmodels.tools.eval_measures import rmse
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from matplotlib import pyplot

#ler os dados
import csv
dados = pd.read_csv('/content/observados - Página1.csv')

#eliminar os warnings das bibliotecas. Configura o Python para ignorar todas as mensagens de aviso que são emitidas durante a execução do código
import warnings
warnings.filterwarnings("ignore")

#gráfico da série
print(dados)
dados.plot(figsize=(15, 6))
plt.title('Geração de Empregos')
plt.xlabel('Meses')
plt.ylabel('')
plt.show()

#funções FAC e FACP

lag_acf = acf(dados, nlags=20)
lag_pacf = pacf(dados, nlags=20)
dados.plot(figsize=(15, 6))
#plt.figure(figsize=(12, 6))
plt.subplot(121)
plt.stem(lag_acf)
plt.title('Função de Autocorrelação')

plt.subplot(122)
plt.stem(lag_pacf)
plt.title('Função de Autocorrelação Parcial')
plt.show()

#Teste Fuller
Teste=adfuller(dados)
adf_statistic = Teste[0]
p_value = Teste[1]

print("Estatística ADF:", adf_statistic)
print("Valor-p:", p_value)

if p_value <= 0.05:
    print("A série é estacionária (p <= 0.05).")
else:
    print("A série não é estacionária (p > 0.05).")

# Teste da média zero para verificar estacionariedade
t_statistic, p_value = stats.ttest_1samp(dados, 0)

if p_value < 0.05:  # Usando um nível de significância de 0,05
    print('A média não é estatisticamente igual a zero. A série não é estacionária.')
else:
    print('A média é estatisticamente igual a zero. A série pode ser estacionária.')

vendas_diff = dados.diff().dropna()

#Teste Dickey Fuller
Teste2=adfuller(vendas_diff)
adf_statistic = Teste2[0]
p_value = Teste2[1]

print("Estatística ADF:", adf_statistic)
print("Valor-p:", p_value)

if p_value <= 0.05:
    print("A série é estacionária (p <= 0.05).")
else:
    print("A série não é estacionária (p > 0.05).")

from statsmodels.tsa.statespace.sarimax import SARIMAX

# Define SARIMA parameters
p, d, q = 1, 1, 2
P, D, Q, s = 1, 1, 1, 12 # Assuming monthly seasonality

# Fit the SARIMA model
model = SARIMAX(dados, order=(p, d, q), seasonal_order=(P, D, Q, s))
results = model.fit()
model

# Forecast future values
forecast_periods = 5 # Forecast the next 12 months
forecast = results.get_forecast(steps=forecast_periods)
forecast_mean = forecast.predicted_mean
forecast_ci = forecast.conf_int()

# Plot the forecast
plt.figure(figsize=(12, 6))
plt.plot(dados, label='Observed')
plt.plot(forecast_mean, label='Forecast', color='red')

plt.title("Forecast")
plt.xlabel("")
plt.ylabel("")
plt.legend()
plt.show()

mod = SARIMAX(dados, order=(1, 1, 2), seasonal_order=(1, 1, 1, 12))
result = mod.fit()
fig = result.predict(start=79, end=88)
fig

print(forecast_mean)

plt.figure(figsize=(12, 8))
plt.plot(dados, label='forecast')
plt.plot(fig)

plt.plot(range(len(dados), len(dados) + forecast_periods), forecast_mean, color='red', label='Previsão')